Repository hurikake06/pet, pull requests merged in 2018-12, with the labels that each got.

#100 stylesheetsコントローラ別読込
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/cg/layouts.scss
  app/assets/stylesheets/layouts.scss
  app/controllers/cg/cg_app_controller.rb
  app/controllers/cg/dm_groups_controller.rb
  app/controllers/cg/dms_controller.rb
  app/controllers/cg/evs_controller.rb
  app/controllers/cg/layouts_controller.rb
  app/controllers/cg/pets_controller.rb
  app/controllers/cg/shares_controller.rb
  app/controllers/cg/users_controller.rb
  app/controllers/cg_layouts_controller.rb
  app/views/layouts/cg_layouts.html.erb
  config/initializers/assets.rb
Labels: enhancement

#107 シェア条件・シェア詳細周り修正
  app/views/cg/shares/host/list.html.erb
  app/views/cg/shares/host/show.html.erb
  app/views/cg/shares/list.html.erb
  app/views/cg/shares/new.html.erb
  app/views/cg/shares/show.html.erb
Labels: enhancement

#110 icon/petのフォルダ名変更
  app/assets/images/icon/animal/cat_1.png
  app/assets/images/icon/animal/cat_2.png
  app/assets/images/icon/animal/cat_3.png
  app/assets/images/icon/animal/cat_4.png
  app/assets/images/icon/animal/cat_5.png
  app/assets/images/icon/animal/cat_6.png
  app/assets/images/icon/animal/dog_1.png
  app/assets/images/icon/animal/dog_2.png
  app/assets/images/icon/animal/dog_3.png
  app/assets/images/icon/animal/dog_4.png
  app/assets/images/icon/animal/dog_5.png
  app/assets/images/icon/animal/dog_6.png
  app/assets/images/icon/animal/dog_7.png
  db/migrate/20180923055611_create_cg_pets.rb
  db/schema.rb
Labels: back, enhancement

#114 新規登録リンク修正
  app/views/cg/users/login.html.erb
Labels: bug

#118 112 layout.scss organize
  app/assets/stylesheets/cg/layouts.scss
Labels: enhancement, front

#119 スライドショー風トップページ
  app/views/cg/cg_app/index.html.erb
  lib/assets/javascripts/slides.js
Labels: front

#120 menu-toggleボタンを押した際の挙動の修正
  app/views/cg/layouts/_header.html.erb
  app/views/cg/layouts/_sidemenu.html.erb
Labels: bug, front

#121 マイページ改修
  app/views/cg/users/host/mypage.html.erb
  app/views/cg/users/mypage.html.erb
  db/seeds.rb
Labels: bug, enhancement, front

#123 最後のスライドとしてログインに飛べる画面を追加
  app/views/cg/cg_app/index.html.erb
Labels: design

#128 シェア詳細画面のcssを整理
  app/assets/stylesheets/cg/layouts.scss
  app/assets/stylesheets/cg/shares.scss
  app/assets/stylesheets/layouts.scss
  app/views/cg/shares/host/show.html.erb
  app/views/cg/shares/show.html.erb
Labels: enhancement, front

#127 スライドの追加
  app/assets/images/slide/cg_logo_serif.png
  app/assets/images/slide/slide_12.png
  app/assets/images/slide/slide_13.png
  app/assets/images/slide/slide_14.png
  app/assets/images/slide/slide_15.png
  app/assets/images/slide/slide_16.png
  app/views/cg/cg_app/index.html.erb
Labels: enhancement

#133 viewにかかれているstyleをstylesheets下のscssファイルに移行した
  app/assets/stylesheets/cg/pets.scss
  app/views/cg/pets/mypage.html.erb
Labels: enhancement, front

#138 シェア周り統一
  app/assets/stylesheets/cg/shares.scss
  app/controllers/cg/cg_app_controller.rb
  app/controllers/cg/pets_controller.rb
  app/controllers/cg/shares_controller.rb
  app/controllers/cg/users_controller.rb
  app/helpers/sessions_helper.rb
  app/helpers/view_helper.rb
  app/models/cg/user.rb
  app/views/cg/layouts/_menu_bar.html.erb
  app/views/cg/layouts/_sidemenu.html.erb
  app/views/cg/pets/show.html.erb
  app/views/cg/shares/host/_list.html.erb
  app/views/cg/shares/host/_show.html.erb
  app/views/cg/shares/host/list.html.erb
  app/views/cg/shares/host/show.html.erb
  app/views/cg/shares/list.html.erb
  app/views/cg/shares/new.html.erb
  app/views/cg/shares/show.html.erb
  app/views/cg/shares/user/_list.html.erb
  app/views/cg/shares/user/_show.html.erb
  config/routes.rb
Labels: back, enhancement

#137 index.html.erbにかかれていたstyleをcg_app.scssに移行した
  app/assets/stylesheets/cg/cg_app.scss
  app/views/cg/cg_app/home.html.erb
  app/views/cg/cg_app/index.html.erb
  app/views/layouts/cg_layouts.html.erb
Labels: enhancement, front

#145 レイアウト切り分け
  app/assets/stylesheets/cg/layouts_default.scss
  app/assets/stylesheets/cg/layouts_nomal.scss
  app/assets/stylesheets/cg/layouts_width_stuffing.scss
  app/controllers/cg/cg_app_controller.rb
  app/controllers/cg/layouts_controller.rb
  app/views/layouts/cg_layouts_nomal.html.erb
  app/views/layouts/cg_layouts_width_stuffing.html.erb
Labels: back

#144 112_メニューバーのstyleを移行
  app/assets/stylesheets/cg/layouts_default.scss
  app/views/cg/layouts/_menu_bar.html.erb
Labels: enhancement, front

#151 page_contentが意図するレイアウトになるように修正
  app/assets/stylesheets/cg/cg_app.scss
  app/assets/stylesheets/cg/layouts_default.scss
  app/assets/stylesheets/cg/layouts_nomal.scss
  app/assets/stylesheets/cg/layouts_width_stuffing.scss
Labels: bug, front

#146 Update navbar style 2
  app/assets/images/icon/etc/b_73.png
  app/views/cg/layouts/_header.html.erb
Labels: design, enhancement, front

#148 58 update pet detail
  app/controllers/cg/pets_controller.rb
  app/views/cg/pets/_edit_form.html.erb
  app/views/cg/pets/edit.html.erb
  config/routes.rb
Labels: back, enhancement

#150 DMグループのユーザ・ペット又はシェアの一意性
  db/migrate/20181126052602_create_cg_dm_groups.rb
  db/schema.rb
Labels: back, enhancement

#152 新規登録時にログイン
  app/controllers/cg/users_controller.rb
Labels: back, enhancement

#156 サイドメニューのcssを移行
  app/assets/stylesheets/cg/layouts_default.scss
  app/views/cg/layouts/_sidemenu.html.erb
Labels: enhancement, front

#165 pets.scss内のscssをページごとに読み込む為の区分け
  app/assets/stylesheets/cg/pets.scss
  app/views/cg/pets/mypage.html.erb
  app/views/cg/pets/show.html.erb
Labels: enhancement, front

#149 134 add search page
  app/assets/javascripts/cg/searchs.coffee
  app/assets/stylesheets/cg/searchs.scss
  app/controllers/cg/searchs_controller.rb
  app/helpers/cg/searchs_helper.rb
  app/views/cg/searchs/index.html.erb
  config/routes.rb
  test/controllers/cg/searchs_controller_test.rb
Labels: back, enhancement, front

#166 新規登録画面のレイアウト改善
  app/assets/stylesheets/cg/users.scss
  app/views/cg/users/new.html.erb
Labels: enhancement, front

#173 ペット新規登録画面のレイアウト改善
  app/assets/stylesheets/cg/pets.scss
  app/views/cg/pets/mypage.html.erb
  app/views/cg/pets/new.html.erb
Labels: enhancement, front

#182 ルーティング修正
  app/controllers/cg/pets_controller.rb
  app/controllers/cg/shares_controller.rb
  app/controllers/cg/users_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/cg/searchs_helper.rb
  app/models/cg/pet.rb
  app/models/cg/user.rb
  app/models/cg/user_dm_group.rb
  app/views/cg/cg_app/home.html.erb
  app/views/cg/cg_app/index.html.erb
  app/views/cg/layouts/_menu_bar.html.erb
  app/views/cg/layouts/_sidemenu.html.erb
  app/views/cg/pets/_new_form.html.erb
  app/views/cg/pets/mypage.html.erb
  app/views/cg/pets/new.html.erb
  app/views/cg/pets/show.html.erb
  app/views/cg/searchs/index.html.erb
  app/views/cg/shares/_new_form.html.erb
  app/views/cg/shares/host/_list.html.erb
  app/views/cg/shares/new.html.erb
  app/views/cg/shares/user/_list.html.erb
  app/views/cg/users/_new_form.html.erb
  app/views/cg/users/edit.html.erb
  app/views/cg/users/login.html.erb
  app/views/cg/users/mypage.html.erb
  app/views/cg/users/new.html.erb
  app/views/cg/users/show.html.erb
  config/routes.rb
Labels: back

#184 #182 対応 pet edit分割
  app/controllers/cg/pets_controller.rb
  app/views/cg/pets/_edit_form.html.erb
  config/routes.rb
Labels: enhancement

#179 ヘッダーのレイアウトをscssに移行した
  app/assets/stylesheets/cg/layouts_default.scss
  app/views/cg/layouts/_header.html.erb
Labels: enhancement, front

#178 細かいミスの修正
  app/assets/stylesheets/cg/layouts_default.scss
Labels: enhancement, front

#191 167 update edit user page
  app/assets/stylesheets/cg/layouts_default.scss
  app/assets/stylesheets/cg/users.scss
  app/assets/stylesheets/mixin.scss
  app/views/cg/users/_edit_form.html.erb
  app/views/cg/users/edit.html.erb
Labels: enhancement, front

#194 shares.scss内のcssの区分け
  app/assets/stylesheets/cg/shares.scss
  app/views/cg/shares/list.html.erb
  app/views/cg/shares/new.html.erb
  app/views/cg/shares/show.html.erb
Labels: enhancement, front

#195 181 add evaluation
  app/controllers/cg/evs_controller.rb
  app/models/cg/ev.rb
  app/models/cg/host_ev.rb
  app/models/cg/user_ev.rb
  app/views/cg/evs/_host_ev_form.html.erb
  app/views/cg/evs/_user_ev_form.html.erb
  app/views/cg/evs/edit.html.erb
  config/routes.rb
  db/migrate/20181126052527_create_cg_evs.rb
  db/schema.rb
  db/seeds/info.rb
  db/seeds/info_type.rb
Labels: back, enhancement
