Repository hurikake06/pet, pull requests merged in 2019-01, with the labels that each got.

#202 199 add dm page
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/channels/dm_channel.rb
  app/controllers/cg/dm_groups_controller.rb
  app/controllers/cg/dms_controller.rb
  app/controllers/cg/users_controller.rb
  app/models/cg/dm.rb
  app/models/cg/user.rb
  app/views/cg/dm_groups/_dm_group.html.erb
  app/views/cg/dm_groups/list.html.erb
  app/views/cg/dm_groups/new.html.erb
  app/views/cg/dm_groups/show.html.erb
  app/views/cg/dm_groups/show.js.erb
  app/views/cg/dm_groups/show_share.html.erb
  app/views/cg/dms/_dm.html.erb
  app/views/cg/dms/_new_form.html.erb
  config/routes.rb
Labels: back

#204 203 upload image icon
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/cg/pets_controller.rb
  app/controllers/cg/users_controller.rb
  app/models/cg/pet.rb
  app/models/cg/user.rb
  app/uploaders/icon_uploader.rb
  app/views/cg/layouts/_sidemenu.html.erb
  app/views/cg/pets/_edit_form.html.erb
  app/views/cg/pets/mypage.html.erb
  app/views/cg/pets/show.html.erb
  app/views/cg/searchs/_pet.html.erb
  app/views/cg/searchs/_user.html.erb
  app/views/cg/users/_edit_form.html.erb
  app/views/cg/users/edit.html.erb
  app/views/cg/users/mypage.html.erb
  db/migrate/20180923055611_create_cg_pets.rb
  db/schema.rb
Labels: back

#188 142 update share detail
  app/controllers/cg/shares_controller.rb
  app/views/cg/shares/_new_form.html.erb
  app/views/cg/shares/edit.html.erb
  app/views/cg/shares/host/_edit_form.html.erb
  app/views/cg/shares/show.html.erb
  app/views/cg/shares/user/_edit_form.html.erb
  config/routes.rb
Labels: back

#205 ホーム画面改善
  app/assets/images/sample/animal/cat_1.jpg
  app/assets/images/sample/animal/cat_2.jpg
  app/assets/images/sample/animal/cat_3.jpg
  app/assets/images/sample/animal/cat_4.jpg
  app/assets/images/sample/animal/cat_5.jpg
  app/assets/images/sample/animal/dog_1.jpg
  app/assets/images/sample/animal/dog_2.jpg
  app/assets/images/sample/animal/dog_3.jpg
  app/assets/images/sample/animal/dog_4.jpg
  app/assets/images/sample/animal/dog_5.jpg
  app/assets/images/sample/animal_low_quality/cat_1.jpg
  app/assets/images/sample/animal_low_quality/cat_2.jpg
  app/assets/images/sample/animal_low_quality/cat_3.jpg
  app/assets/images/sample/animal_low_quality/cat_4.jpg
  app/assets/images/sample/animal_low_quality/cat_5.jpg
  app/assets/images/sample/animal_low_quality/dog_1.jpg
  app/assets/images/sample/animal_low_quality/dog_2.jpg
  app/assets/images/sample/animal_low_quality/dog_3.jpg
  app/assets/images/sample/animal_low_quality/dog_4.jpg
  app/assets/images/sample/animal_low_quality/dog_5.jpg
  app/assets/images/sample/person/man_1.jpg
  app/assets/images/sample/person/man_2.jpg
  app/assets/images/sample/person/man_3.jpg
  app/assets/images/sample/person/man_4.jpg
  app/assets/images/sample/person/woman_1.jpg
  app/assets/images/sample/person/woman_2.jpg
  app/assets/stylesheets/cg/cg_app.scss
  app/assets/stylesheets/cg/layouts_default.scss
  app/controllers/cg/cg_app_controller.rb
  app/views/cg/cg_app/home.html.erb
  db/schema.rb
  db/seeds.rb
Labels: enhancement, front

#211 フッターレイアウト改善
  app/assets/stylesheets/cg/layouts_default.scss
  app/views/cg/layouts/_footer.html.erb
Labels: enhancement, front

#215 Add show share info
  app/assets/images/icon/etc/b_74.png
  app/controllers/cg/evs_controller.rb
  app/controllers/cg/shares_controller.rb
  app/models/cg/pet.rb
  app/models/cg/user.rb
  app/views/cg/pets/mypage.html.erb
  app/views/cg/shares/_show_info.html.erb
  app/views/cg/shares/edit.html.erb
  app/views/cg/shares/host/_edit_form.html.erb
  app/views/cg/shares/show.html.erb
  app/views/cg/shares/user/_edit_form.html.erb
  app/views/cg/shares/user/_list.html.erb
  app/views/cg/users/mypage.html.erb
  db/migrate/20180923055440_create_cg_users.rb
  db/migrate/20180923055549_create_cg_types.rb
  db/migrate/20180923055611_create_cg_pets.rb
  db/migrate/20181030025720_create_cg_shares.rb
  db/migrate/20181031052337_create_cg_user_details.rb
  db/migrate/20181105052849_create_cg_pet_details.rb
  db/migrate/20181126052527_create_cg_evs.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/info.rb
  db/seeds/info_type.rb
  db/seeds/type.rb
Labels: back

#214 サイドバーにある不要なスクロールバーを削除
  app/assets/stylesheets/cg/layouts_default.scss
Labels: enhancement, front

#217 216 optimization menubar
  app/assets/images/icon/etc/menubar_to_home.png
  app/assets/images/icon/etc/menubar_to_mypage.png
  app/assets/images/icon/etc/menubar_to_search.png
  app/assets/images/icon/etc/menubar_to_sharelist.png
  app/assets/stylesheets/cg/layouts_default.scss
  app/views/cg/layouts/_menu_bar.html.erb
Labels: enhancement, front

#218 157 update form
  app/assets/stylesheets/cg/shares.scss
  app/assets/stylesheets/cg/users.scss
  app/assets/stylesheets/mixin.scss
  app/controllers/cg/shares_controller.rb
  app/views/cg/shares/_new_form.html.erb
  app/views/cg/shares/host/_list.html.erb
  app/views/cg/shares/host/_show.html.erb
  app/views/cg/shares/new.html.erb
  app/views/cg/shares/user/_list.html.erb
  app/views/cg/shares/user/_show.html.erb
  app/views/cg/users/_login_form.html.erb
  app/views/cg/users/edit.html.erb
  app/views/cg/users/login.html.erb
  public/uploads/cg/pet/icon/1/dog_1.jpg
  public/uploads/cg/pet/icon/10/cat_5.jpg
  public/uploads/cg/pet/icon/2/dog_2.jpg
  public/uploads/cg/pet/icon/3/dog_3.jpg
  public/uploads/cg/pet/icon/4/dog_4.jpg
  public/uploads/cg/pet/icon/5/dog_5.jpg
  public/uploads/cg/pet/icon/6/cat_1.jpg
  public/uploads/cg/pet/icon/7/cat_2.jpg
  public/uploads/cg/pet/icon/8/cat_3.jpg
  public/uploads/cg/pet/icon/9/cat_4.jpg
  public/uploads/cg/user/icon/1/man_1.jpg
  public/uploads/cg/user/icon/2/man_2.jpg
  public/uploads/cg/user/icon/3/man_3.jpg
  public/uploads/cg/user/icon/4/woman_1.jpg
  public/uploads/cg/user/icon/5/man_4.jpg
  public/uploads/cg/user/icon/6/woman_2.jpg
Labels: enhancement, front

#225 222 update mypage
  app/assets/stylesheets/cg/users.scss
  app/views/cg/users/mypage.html.erb
Labels: enhancement, front

#228 マイページと自分のペットページにラベル追加
  app/assets/stylesheets/cg/pets.scss
  app/assets/stylesheets/cg/users.scss
  app/views/cg/pets/mypage.html.erb
  app/views/cg/users/mypage.html.erb
Labels: enhancement, front

#229 199 style dm page
  app/assets/stylesheets/cg/dm_groups.scss
  app/assets/stylesheets/cg/layouts_default.scss
  app/assets/stylesheets/cg/shares.scss
  app/channels/dm_channel.rb
  app/channels/share_alert_channel.rb
  app/controllers/cg/dm_groups_controller.rb
  app/controllers/cg/dms_controller.rb
  app/controllers/cg/shares_controller.rb
  app/helpers/cg/shares_helper.rb
  app/helpers/view_helper.rb
  app/models/cg/share.rb
  app/models/cg/user.rb
  app/views/cg/dm_groups/show.html.erb
  app/views/cg/dm_groups/show.js.erb
  app/views/cg/dm_groups/show_share.html.erb
  app/views/cg/dms/_dm.html.erb
  app/views/cg/dms/_new_form.html.erb
  app/views/cg/shares/host/_edit_info.html.erb
  app/views/cg/shares/host/_list.html.erb
  app/views/cg/shares/list.html.erb
  app/views/cg/shares/user/_edit_form.html.erb
  app/views/cg/shares/user/_edit_info.html.erb
  app/views/cg/shares/user/_list.html.erb
  app/views/module/_modal.html.erb
  config/routes.rb
  db/migrate/20181126052627_create_cg_dms.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#235 faviconの追加
  app/assets/images/icon/etc/favicon.ico
  app/views/layouts/cg_layouts_nomal.html.erb
  app/views/layouts/cg_layouts_width_stuffing.html.erb
Labels: enhancement, front

#236 233 update share new form 2
  app/assets/stylesheets/cg/shares.scss
  app/views/cg/shares/_new_form.html.erb
  app/views/cg/shares/new.html.erb
Labels: enhancement, front

#241 238 update dm layout
  app/assets/stylesheets/cg/dm_groups.scss
  app/views/cg/shares/_show_info.html.erb
  app/views/cg/shares/host/_edit_info.html.erb
  app/views/cg/shares/user/_edit_form.html.erb
  app/views/cg/shares/user/_edit_info.html.erb
  db/seeds/info.rb
Labels: enhancement, front

#247 242 update dm arrangement
  app/assets/images/icon/etc/arrow_2.png
  app/assets/stylesheets/cg/dm_groups.scss
  app/views/cg/dm_groups/show_share.html.erb
  app/views/cg/shares/_show_prof.html.erb
  app/views/cg/shares/host/_edit_form.html.erb
  app/views/cg/shares/host/_edit_info.html.erb
  app/views/cg/shares/user/_edit_form.html.erb
  app/views/cg/shares/user/_edit_info.html.erb
Labels: enhancement, front

#253 pet_showページの文字サイズ大きく
  app/assets/stylesheets/cg/pets.scss
Labels: enhancement, front

#254 設定情報を環境変数に移行
  Gemfile
  Gemfile.lock
  config/database.yml
Labels: enhancement
